name: Build and publish docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x     

    - name: dotnet restore
      run: dotnet restore ./src/ThermostatScheduler.WebApp/ThermostatScheduler.WebApp.csproj

    - name: dotnet publish
      run: dotnet publish ./src/ThermostatScheduler.WebApp/ThermostatScheduler.WebApp.csproj --configuration Release --no-restore --output ./publish

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: ./publish
        file: ./src/Dockerfile
        push: true
        tags: hladik/thermostat-scheduler:$GITHUB_RUN_ID,hladik/thermostat-scheduler:latest


