name: Build and publish docker image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0' 
    - name: Install dependencies
      run: dotnet restore ./src/ThermostatScheduler.WebApp/ThermostatScheduler.WebApp.csproj
    - name: Build
      run: dotnet publish ./src/ThermostatScheduler.WebApp/ThermostatScheduler.WebApp.csproj --no-restore
